Added configurable border width and disable flag for the shadow on tapping (helpful if you want a flat button and the elevation is 0)
Frezyx/group_button pull request #107
Opened 2024-01-10 16:56 UTC by JaseElder

Added configurable border width and disable flag for the shadow on tapping (helpful if you want a flat button and the elevation is 0)

2024-02-15 08:01 UTC, Frezyx requested changes
Hello @JaseElder ! 
Thanks a lot for this contribution 

Can we fix review issues before merge ?

2024-02-15 14:29 UTC, JaseElder commented on lib/src/group_button_body.dart
> +  final bool? disableTappingShadow;
Yes, good idea! I'll amend.

2024-02-15 16:02 UTC, JaseElder commented
I'm not sure whether I've done the right thing with this PR, but it looks like the new changes are there...

2024-05-30 02:19 UTC, jenyang2 commented
When does border with apply?

2024-05-30 13:13 UTC, JaseElder commented
> When does border width apply?

Border width is by default set to 1, but a borderWidth can be provided in GroupButtonOptions() if it needs to be other than 1.

2024-09-18 16:54 UTC, Nirsu commented
@Frezyx Any news on this PR ?

2024-09-19 15:36 UTC, Frezyx requested changes

2024-09-19 15:36 UTC, Frezyx commented on lib/src/options/group_button_options.dart
> +    this.tappingShadowColor = defaultTappingShadowColor,
tappingShadowColor must be null by default

2024-09-19 15:40 UTC, Frezyx commented
Hello @JaseElder !
Thank you for this contribution ❤️ 

Sorry for delay 🥶

2024-09-19 15:41 UTC, Frezyx approved these changes

2024-09-19 15:44 UTC, merged

2024-10-03 14:47 UTC, JaseElder commented
> Hello @JaseElder ! Thank you for this contribution ❤️
> 
> Sorry for delay 🥶

No worries!

Is there something special that has to happen to have this release appear on pub.dev? It's still showing group_button: ^5.3.4 for me

2025-02-04 16:19 UTC, JaseElder commented
> > Hello @JaseElder ! Thank you for this contribution ❤️
> > Sorry for delay 🥶
> 
> @Frezyx No worries!
> 
> Is there something special that has to happen to have this release appear on pub.dev? It's still showing group_button: ^5.3.4 for me

Hi @Frezyx I'm still seeing 5.3.4 on pub.dev. Is it possible to push this release up?

2025-04-15 20:37 UTC, JaseElder commented
Hi @Frezyx ,

Just doing some admin and noticed that 5.4.0 is still not published on pub.dev. Is it possible for you to push it up?
Thanks.