Add TextAlign and Padding options
Frezyx/group_button pull request #46
Opened 2021-09-29 18:40 UTC by wer-mathurin

2021-09-29 18:41 UTC, wer-mathurin commented
@Frezyx Can you look at those proposed changes, they are not breaking changes, just more options :-)

2021-09-29 19:16 UTC, Frezyx requested changes
Hello @wer-mathurin !
Thank you for propose this changes. 

I will merge it when you fix my review comments

2021-09-29 19:16 UTC, Frezyx commented on lib/group_button.dart
> +  /// [TextAlign] the text alignment to use in the buttons for the [GroupButton]
buttons text alignment

2021-09-29 19:16 UTC, Frezyx commented on lib/group_button.dart
> +  /// [EdgeInsets] the text alignment to use in the buttons for the [GroupButton]
inner padding of buttons

2021-09-29 19:17 UTC, Frezyx commented
And if it's not difficult for you
Add this new fields in [README](https://github.com/Frezyx/group_button/blob/master/README.md) file

2021-10-01 03:36 UTC, wer-mathurin commented
@Frezyx all request resolve in the last commit

2021-10-01 05:57 UTC, Frezyx approved these changes

2021-10-01 05:58 UTC, Frezyx commented
Thank you for your contribution !

2021-10-01 06:15 UTC, merged