Adding event on disabled items
Frezyx/group_button pull request #59
Opened 2022-01-06 01:54 UTC by gnassro

Pull request for this feature [https://github.com/Frezyx/group_button/issues/58](https://github.com/Frezyx/group_button/issues/58)

2022-01-06 13:25 UTC, Frezyx requested changes

2022-01-06 13:25 UTC, Frezyx commented on lib/src/group_button_base.dart
> +        onDisablePressed: (index,) => onDisablePressed(index),
unnecessary comma

2022-01-06 13:25 UTC, Frezyx commented on lib/src/group_custom_button.dart
> +              child: Padding(
This type of widgets build is huge and need in much place to code 
Please simplify this code

2022-01-06 17:43 UTC, gnassro commented
what's wrong in this now ? somthing missing ?

2022-01-06 23:33 UTC, Frezyx approved these changes

2022-01-06 23:59 UTC, merged

2022-01-07 00:05 UTC, Frezyx commented
All is good!
Thank you for your contribution @gnassro

2022-01-07 13:49 UTC, gnassro commented
> All is good! Thank you for your contribution @gnassro

Thank you too for this package.
i think this pull request must linked to this [issue](https://github.com/Frezyx/group_button/issues/58)